### PR TITLE
metal: Implicit CAMetalLayer allocation

### PR DESCRIPTION
**Pull request by msiglreith**
Allocates implicitly a CAMetalLayer in case the provided window handle doesnt have one.
Experimental as not tested - one ugly point is that the CAMetalLayer doesn't get destroyed I think

Looking for feedback
cc https://github.com/norse-rs/ash-window/issues/8

### CODE REVIEW

**Comment by Ralith** [comment]
Will try to coordinate with a macOS user to test this in the near future. Thanks!

**Comment by Friz64** [comment]
While i don't have a mac, i am very interested in getting this fixed. Because of that i prepared a very simple test for mac users which should hopefully suffice at https://github.com/Friz64/ash-window-pr-9-test. Just clone it and do `cargo run`.

**Comment by nathanfdunn** [comment]
@Friz64 I am also interested in getting this fixed. Here are the results from my MacBook Pro, macOS 10.15.3

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/ash-window-9`
Error: VkError(ERROR_EXTENSION_NOT_PRESENT)
```

**Comment by Friz64** [comment]
Hmm, weird. I guess it's because your version of MoltenVK is outdated. Try to update your Vulkan SDK.

**Comment by nathanfdunn** [comment]
Upgrading to latest (1.2.135.0) seemed to do the trick!...I think...was it supposed to display anything?

image

**Comment by Friz64** [comment]
It is not supposed to display anything but if you get output like `surface: 0x555cd87e2d10`, it works!

**Comment by nathanfdunn** [comment]
`surface: 0x7fb930474290` Looks good!

**Comment by vvcarvalho** [comment]
Also tested on my MacBook Pro on macOS 10.15.4 with similar results to @nathanfdunn.

**Comment by Ralith** [comment]
My larger application at https://github.com/Ralith/hypermine/tree/macos-test reportedly opens a window and draws to it without errors, but the output is not correct. I'm guessing I'm hitting a MoltenVK bug which I'm unfortunately not equipped to investigate, but it does seem like this is a step in the right direction at least. I'd be happiest if someone was able to get some actual graphics beyond a solid color on screen, though.

**Comment by Friz64** [comment]
Well, all my test does for now is create a `Surface` without errors. I guess i could put the work in and make it display a triangle.

**Comment by Ralith** [comment]
Perhaps adapting an ash example would be easiest?

**Comment by Friz64** [comment]
The [test repo](https://github.com/Friz64/ash-window-pr-9-test) now displays a triangle!
You can now also enable `VK_EXT_debug_utils` using `cargo run -- -v`.

---



> Perhaps adapting an ash example would be easiest?

I ended up just porting the [erupt triangle example](https://gitlab.com/Friz64/erupt/-/blob/master/erupt-examples/src/bin/triangle.rs) because all it's dependencies are up to date and it's all in one file. It was originally created using https://vulkan-tutorial.com.

**Comment by nathanfdunn** [comment]
@Friz64 

```
$ cargo run -- -v
   Compiling ash-window-9 v0.1.0 (/Users/default/Projects/aash-window-pr-9-test)
error[E0599]: no associated item named `MAX` found for type `u64` in the current scope
   --> src/main.rs:507:77
    |
507 |                     .wait_for_fences(&[in_flight_fences[frame]], true, u64::MAX)
    |                                                                             ^^^ associated item not found in `u64`
    |
help: you are looking for the module in `std`, not the primitive type
    |
507 |                     .wait_for_fences(&[in_flight_fences[frame]], true, std::u64::MAX)
    |                                                                        ^^^^^^^^^^^^^

error[E0599]: no associated item named `MAX` found for type `u64` in the current scope
   --> src/main.rs:514:26
    |
514 |                     u64::MAX,
    |                          ^^^ associated item not found in `u64`
    |
help: you are looking for the module in `std`, not the primitive type
    |
514 |                     std::u64::MAX,
    |                     ^^^^^^^^^^^^^

error[E0599]: no associated item named `MAX` found for type `u64` in the current scope
   --> src/main.rs:524:80
    |
524 |                 unsafe { device.wait_for_fences(&[image_in_flight], true, u64::MAX) }.unwrap();
    |                                                                                ^^^ associated item not found in `u64`
    |
help: you are looking for the module in `std`, not the primitive type
    |
524 |                 unsafe { device.wait_for_fences(&[image_in_flight], true, std::u64::MAX) }.unwrap();
    |                                                                           ^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ash-window-9`.

To learn more, run the command again with --verbose.
```

**Comment by Friz64** [comment]
Update your Rust to the newest version. (1.43.0)
I'm using features that were just introduced in it.

**Comment by nathanfdunn** [comment]
Running without errors now!

Console output in case it's useful:
```
$cargo run -- -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/ash-window-9 -v`
Using physical device: "Intel Iris Graphics"
```

image

**Comment by Ralith** [comment]
Should this be merged? It seems like we've validated it.

**Comment by Friz64** [comment]
Pinging @msiglreith

**Comment by msiglreith** [comment]
Thanks all for testing! Will release a new version `0.4.1` shortly

**Comment by Ralith** [comment]
Thanks a ton for your work on this!

**Pull request merged**
